### ISSUE TITLE
keyword argument in url not working for listapiview

### ISSUE THREAD

**Issue by RiflerRick** [MojoJojo6/UserService#2]
@PrIyanshu-Bhatnagar please have a look at User/urls.py and User/views.py

`lookup_field` is mentioned and the `urls.py` file has the keyword argument specified.
However on requesting at
`http://localhost:8000/User/users?id=1`
I am not getting the first id, I am getting the entire list.

**Comment by PrIyanshu-Bhatnagar** [comment]
@RiflerRick Just for the sake of answering. lookup_field is used when we deal with 1 object (User.objects.get(**lookup_field)) in Retrieve/Update/Delete API View. And URL param `http://localhost:8000/Users/users/<int:id>/ `will be written as `http://localhost:8000/Users/users/1/`
